
version: '2'

services:
  downloader:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /mnt/storage/media/music:/mnt/storage/media/music
      - /mnt/storage/media/pelis:/mnt/storage/media/pelis
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - kamilo

networks:
  kamilo:
    external:
      name: kamilo
